### ISSUE TITLE
Cytoscape Error

### ISSUE THREAD

**Issue by ZAJHammond** [secviz/davix#11]
Priority: High

We are currently fetching an install script which provides a GUI for the user to install Cytoscape. If we want to auto install it then we need to go another route, see http://chianti.ucsd.edu/svn/cytoscape/trunk/README.txt for details but note I time out when trying to connect to the svn repo.

svn co http://chianti.ucsd.edu/svn/cytoscape/trunk cytoscape

**Comment by zrlram** [comment]
I believe this is fixed. Use -q to install Cytoscape.
